version: "3.7"

services:
  app:
    build: .
    environment:
      - MICRO_QR_TOP_REDIRECT
    volumes:
      - ./log/:/app/log/
      - $MICRO_QR_SOCKET_DIRECTORY_PATH:/socket/
    restart: always
