name: Docker Build
run-name: Docker Build name
on:
  push:
    paths-ignore: 
      - 'build/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job's status is ${{ job.status }}."
      - uses: actions/checkout@v3
      - run: ls -a
      - run: ls -a ../
      - run: pwd
      - run: echo 'aaa' > abc.txt
